services:
  app:
    build: .
    container_name: llm_agent_analyzer
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    env_file:
      - .env

volumes:
  sqlite_data: