from enum import Enum

class TraceEventType(str, Enum):
    RUN_STARTED = "RUN_STARTED"
    LLM_DECISION = "LLM_DECISION"
    TOOL_SELECTED = "TOOL_SELECTED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_SUCCEEDED = "TOOL_SUCCEEDED"
    TOOL_FAILED = "TOOL_FAILED"
    RETRY_ATTEMPT = "RETRY_ATTEMPT"
    OBSERVATION = "OBSERVATION"
    FINAL_RESPONSE = "FINAL_RESPONSE"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    MAX_STEPS_REACHED = "MAX_STEPS_REACHED"

class ErrorType(str, Enum):
    NONE = "NONE"
    WRONG_TOOL_SELECTION = "WRONG_TOOL_SELECTION"
    INVALID_TOOL_INPUT = "INVALID_TOOL_INPUT"
    TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
    TIMEOUT = "TIMEOUT"
    EMPTY_RESULT = "EMPTY_RESULT"
    DATABASE_ERROR = "DATABASE_ERROR"
    MAX_STEPS_EXCEEDED = "MAX_STEPS_EXCEEDED"
    RETRY_EXHAUSTED = "RETRY_EXHAUSTED"
    INVALID_LLM_RESPONSE = "INVALID_LLM_RESPONSE"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

class RunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"